services:
  web1:
    image: nginx:alpine
    container_name: web1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web1.rule=Host(`web1.localhost`)"
      - "traefik.http.services.web1.loadbalancer.server.port=80"
    networks:
      - traefik-net  # Attach to the shared network

  web2:
    image: nginx:alpine
    container_name: web2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web2.rule=Host(`web2.localhost`)"
      - "traefik.http.services.web2.loadbalancer.server.port=80"
    networks:
      - traefik-net  # Attach to the shared network

networks:
  traefik-net:
    external: true  # Use the shared network

