services:
  web1.localhost:
    image: nginx:alpine
    container_name: web1.localhost
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web1-localhost.rule=Host(`web1.localhost`)"
      - "traefik.http.services.web1-localhost.loadbalancer.server.port=80"
    networks:
      - traefik-net

  web1.mylocal:
    image: nginx:alpine
    container_name: web1.mylocal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web1-mylocal.rule=Host(`web1.mylocal`)"
      - "traefik.http.services.web1-mylocal.loadbalancer.server.port=80"
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true  # Use the shared network

